import type { Metadata } from "next";
import { ArrowRight, Check, MessageCircle } from "lucide-react";
import { SiteHeader } from "@/components/site-header";
import { SiteFooter } from "@/components/site-footer";
import { EnquiryActions } from "@/components/enquiry-actions";
import { enquiryLinks } from "@/lib/company";
import { siteOrigin } from "@/lib/seo";
import { sitePath } from "@/lib/site-path";

const pageUrl = `${siteOrigin}/shipping-from-china-to-kenya`;
const title = "Shipping from China to Kenya | Mombasa Sea Freight & Project Cargo";
const description = "Plan shipping from China to Kenya via Mombasa: FCL, LCL, breakbulk, heavy machinery and project cargo, with China pickup and Nairobi delivery coordination.";

export const metadata: Metadata = {
  title, description, alternates: { canonical: pageUrl },
  openGraph: { title, description, url: pageUrl, type: "website", images: [{ url: `${siteOrigin}/images/project-cargo.webp`, alt: "Project cargo shipping from China to Kenya" }] },
};

const faqs = [
  { question: "How can I ship goods from China to Kenya?", answer: "FCL can suit container-sized orders, LCL can suit smaller general cargo, and flat rack, breakbulk or other project solutions may be assessed for heavy machinery. Select the method using the final packed cargo, urgency and destination scope." },
  { question: "Which port is used for shipping from China to Kenya?", answer: "Mombasa is Kenya's main seaport and a common gateway for China-origin cargo. The plan should also consider clearance, onward transport and whether delivery is required to Nairobi or another inland destination." },
  { question: "Can TengYoda coordinate delivery from Mombasa to Nairobi?", answer: "Destination delivery can be assessed through a local partner when requested. The quotation must define whether it includes port-to-port freight only or also clearance support, release and inland delivery." },
  { question: "How long does shipping from China to Kenya take?", answer: "Timing varies with the Chinese loading port, carrier route, direct or transshipment service, schedule, port conditions and clearance. A current routing should be checked for every shipment." },
  { question: "Can heavy machinery be shipped from China to Mombasa?", answer: "Yes, subject to carrier and port acceptance. Provide verified dimensions, weight, photographs, lifting points, centre of gravity, packing and operability so suitable container, flat-rack, RoRo or breakbulk possibilities can be assessed." },
  { question: "What is needed for a China-to-Kenya quote?", answer: "Provide the cargo description, packages, dimensions, weights, pickup city, ready date and destination. State whether the requirement ends at Mombasa or includes clearance and delivery to Nairobi or another address." },
];

const schemas = [
  { "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Home", item: `${siteOrigin}/` }, { "@type": "ListItem", position: 2, name: "Shipping from China to Kenya", item: pageUrl }] },
  { "@context": "https://schema.org", "@type": "Service", "@id": `${pageUrl}#service`, name: "Shipping from China to Kenya", serviceType: "International freight forwarding from China to Kenya", url: pageUrl, provider: { "@id": `${siteOrigin}/#organization`, name: "TengYoda Supply Chain Co., Ltd." }, areaServed: { "@type": "Country", name: "Kenya" }, description, hasOfferCatalog: { "@type": "OfferCatalog", name: "China-to-Kenya freight options", itemListElement: ["FCL sea freight", "LCL sea freight", "Breakbulk shipping", "Heavy machinery shipping", "Project cargo coordination", "Mombasa to Nairobi delivery coordination"].map(name => ({ "@type": "Offer", itemOffered: { "@type": "Service", name } })) } },
  { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: faqs.map(item => ({ "@type": "Question", name: item.question, acceptedAnswer: { "@type": "Answer", text: item.answer } })) },
];

function JsonLd({ data }: { data: object }) { return <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(data).replace(/</g, "\\u003c") }} />; }

export default function KenyaShippingPage() {
  const quoteUrl = enquiryLinks("shipping from China to Kenya").whatsapp;
  const options = [
    ["FCL container shipping", "For container-sized cargo, with China pickup, origin handling and Mombasa port or agreed onward coordination."],
    ["LCL consolidation", "For smaller shipments, including supplier receiving and consolidation in China before export."],
    ["Breakbulk cargo", "For machinery or units that cannot fit a standard container, subject to vessel and lifting acceptance."],
    ["Flat rack & special equipment", "For out-of-gauge cargo when specialist container equipment is technically suitable."],
    ["Heavy machinery shipping", "A route and handling review using verified dimensions, weight, lifting points and operability."],
    ["Nairobi delivery coordination", "An optional local handoff with clearance, transport and unloading scope defined before booking."],
  ];
  return <div className="site blog-site nigeria-page" id="top">{schemas.map((schema, index) => <JsonLd data={schema} key={index} />)}<SiteHeader active="services" /><main id="main-content" tabIndex={-1}>
    <section className="blog-hero service-hero editorial-hero nigeria-hero page-enter"><img className="editorial-photo" src={sitePath("/images/project-cargo.webp")} alt="Project cargo shipping from China to Kenya" width={1672} height={941} fetchPriority="high" /><div className="editorial-shade" /><div className="wrap"><nav className="blog-breadcrumb" aria-label="Breadcrumb"><a href={sitePath("/")}>Home</a><span>/</span><span>Shipping from China to Kenya</span></nav><span className="kicker light"><i />CHINA → KENYA FREIGHT</span><h1>Shipping from China to Kenya</h1><p>Plan FCL, LCL, breakbulk, heavy machinery and project cargo through Mombasa—with China pickup and optional Nairobi delivery coordination based on the actual shipment.</p><div className="nigeria-hero-actions"><a className="button accent" href="#quote-checklist">Prepare a quote request<ArrowRight /></a><a className="button outline-light" href={quoteUrl} target="_blank" rel="noreferrer">WhatsApp Vinson<MessageCircle /></a></div></div></section>
    <section className="nigeria-facts"><div className="wrap"><div><small>ORIGIN</small><strong>Major ports and factories across China</strong></div><div><small>KENYA GATEWAY</small><strong>Mombasa</strong></div><div><small>INLAND DESTINATION</small><strong>Nairobi and other locations</strong></div><div><small>CARGO</small><strong>Containers · Machinery · Project cargo</strong></div></div></section>
    <section className="section nigeria-overview"><div className="wrap nigeria-content-grid"><aside className="nigeria-toc"><h2>On this page</h2><nav><a href="#options">Shipping options</a><a href="#ports">Mombasa routing</a><a href="#machinery">Heavy machinery</a><a href="#process">Shipping process</a><a href="#quote-checklist">Quote checklist</a><a href="#faq">Questions</a></nav></aside><div className="nigeria-copy"><span className="kicker"><i />ROUTE OVERVIEW</span><h2>A practical China-to-Kenya shipping plan.</h2><p className="service-lead">TengYoda coordinates supplier pickup, warehouse or port handoffs, export preparation and international freight. The plan is built around final cargo measurements, Mombasa arrival requirements and any requested inland handoff.</p><div className="nigeria-note"><strong>Define the destination scope clearly</strong><p>Port freight does not automatically include Kenyan clearance, destination charges, inland transport or unloading. Confirm responsibilities and import requirements before shipment.</p></div></div></div></section>
    <section className="section nigeria-options" id="options"><div className="wrap"><div className="nigeria-heading"><span className="kicker"><i />FREIGHT OPTIONS</span><h2>FCL, LCL and specialist cargo solutions.</h2><p>The appropriate method depends on volume, dimensions, weight, cargo characteristics, carrier acceptance and delivery scope.</p></div><div className="scope-grid nigeria-service-grid">{options.map(([name, copy], index) => <article key={name}><span>0{index + 1}</span><Check /><h3>{name}</h3><p>{copy}</p></article>)}</div></div></section>
    <section className="section nigeria-ports" id="ports"><div className="wrap nigeria-split"><div><span className="kicker"><i />MOMBASA & INLAND ROUTING</span><h2>Use Mombasa as the gateway, then plan the inland handoff.</h2><p>Potential China loading ports include Shanghai, Ningbo, Shenzhen, Guangzhou/Nansha, Qingdao and Tianjin. Supplier location, cargo type and carrier service determine the practical origin.</p><p>Cargo continuing to Nairobi needs a separate clearance, release, inland transport and unloading plan. Routing may be direct or transshipped and is confirmed when quoting.</p></div><figure><img src={sitePath("/route-images/china-to-kenya-route.png")} alt="Route map from major China ports to Mombasa, Kenya" width={1536} height={1024} loading="lazy" /><figcaption>Route visualization based on named port coordinates; carrier, routing and timing are confirmed per shipment.</figcaption></figure></div></section>
    <section className="section nigeria-project" id="machinery"><div className="wrap nigeria-split nigeria-split-reverse"><div><span className="kicker light"><i />HEAVY & PROJECT CARGO</span><h2>Plan machinery around handling limits.</h2><p>Heavy or oversized units need a coordinated origin, vessel and Mombasa discharge plan.</p><ul><li><Check />Verify dimensions and gross weight</li><li><Check />Provide lifting points and centre of gravity</li><li><Check />Confirm machine operability</li><li><Check />Review factory loading and China access</li><li><Check />Confirm Mombasa discharge and collection equipment</li></ul></div><div className="nigeria-project-card"><small>TECHNICAL REVIEW</small><strong>5</strong><span>essential checks</span><dl><div><dt>Dimensions</dt><dd>Verified</dd></div><div><dt>Weight</dt><dd>Per piece</dd></div><div><dt>Lifting</dt><dd>Points + COG</dd></div><div><dt>Access</dt><dd>China + Kenya</dd></div><div><dt>Acceptance</dt><dd>Carrier confirmed</dd></div></dl></div></div></section>
    <section className="section nigeria-process" id="process"><div className="wrap"><div className="nigeria-heading"><span className="kicker"><i />HOW IT WORKS</span><h2>From China supplier to Kenyan handoff.</h2></div><ol>{[["Share the cargo", "Send cargo, sizes, weights, pickup points, ready date and destination."],["Review the method", "Compare FCL, LCL, flat rack, breakbulk or another suitable solution."],["Define the scope", "Confirm China origin, ocean freight and requested Kenya destination tasks."],["Coordinate in China", "Arrange agreed collection, export preparation and carrier handoff."],["Prepare arrival", "Share documents for Mombasa clearance, release and any inland delivery."]].map(([heading, copy], index) => <li key={heading}><span>0{index + 1}</span><div><h3>{heading}</h3><p>{copy}</p></div></li>)}</ol></div></section>
    <section className="section nigeria-quote" id="quote-checklist"><div className="wrap nigeria-content-grid"><div><span className="kicker"><i />BEFORE YOU ENQUIRE</span><h2>Send the information needed for a useful quote.</h2><p>State whether the shipment ends at Mombasa or requires an inland handoff.</p><EnquiryActions topic="shipping from China to Kenya" /></div><ul>{["Cargo description and HS code if known", "Packages, dimensions and weights", "Supplier location and ready date", "Mombasa or final Kenyan address", "Photos and packing method", "Machinery lifting points and operability", "Requested Incoterm and service scope", "Any controlled cargo characteristics"].map(item => <li key={item}><Check />{item}</li>)}</ul></div></section>
    <section className="section nigeria-faq" id="faq"><div className="wrap nigeria-content-grid"><div><span className="kicker"><i />FAQ</span><h2>China-to-Kenya shipping questions.</h2><p>Rates, schedules and acceptance are confirmed shipment by shipment.</p></div><div>{faqs.map(item => <details key={item.question}><summary>{item.question}<span>+</span></summary><p>{item.answer}</p></details>)}</div></div></section>
    <section className="blog-cta"><div className="wrap"><div><span className="kicker light"><i />A DIRECT CONVERSATION WITH VINSON</span><h2>Planning a shipment from China to Kenya?</h2><p>Share the cargo and destination for a Mombasa or inland-delivery assessment.</p></div><EnquiryActions topic="shipping from China to Kenya" /></div></section>
  </main><SiteFooter /><a className="float-wa" href={quoteUrl} target="_blank" rel="noreferrer" aria-label="Contact Vinson on WhatsApp"><MessageCircle /></a></div>;
}
