export type CountryRoute = {
  route: string;
  country: string;
  shortName: string;
  ports: string[];
  inland: string;
  focus: string[];
  intro: string;
  importNote: string;
  optionNotes: string[];
  routingNotes: string[];
  importChecks: string[];
  localFaqs: { q: string; a: string }[];
};

export const countryRoutes: CountryRoute[] = [
  { route: "shipping-from-china-to-usa", country: "the United States", shortName: "USA", ports: ["Los Angeles / Long Beach", "New York / New Jersey", "Savannah", "Houston"], inland: "US inland delivery points", focus: ["FCL", "LCL", "Air freight", "Amazon and commercial cargo"], intro: "Match the US gateway to the final delivery region, cargo profile and complete destination-cost scope.", importNote: "The US importer should confirm classification, admissibility, customs bond and any agency-specific requirements with a licensed customs broker before shipment.", optionNotes: ["Dedicated containers for larger orders, with the port and inland rail or truck plan selected together.", "Consolidated ocean freight for smaller general cargo, subject to warehouse acceptance and destination charges.", "Airport-to-airport or coordinated delivery options for urgent cargo after chargeable weight and acceptance checks.", "Commercial and FBA-bound cargo needs a defined consignee, importer, appointment and final-delivery plan; TengYoda does not act as the importer."], routingNotes: ["Los Angeles and Long Beach commonly support West Coast and western inland destinations.", "New York / New Jersey and Savannah can suit eastern destinations; Houston can suit Gulf-region cargo.", "The lowest ocean rate may not produce the lowest delivered cost once rail, trucking and destination handling are included."], importChecks: ["Importer of record and licensed customs broker confirmed", "HTS classification, customs bond and admissibility reviewed", "Any FDA, FCC, EPA, USDA or other agency scope checked", "Final warehouse, commercial address or FBA appointment requirements defined"], localFaqs: [{ q: "Which US coast should I use?", a: "The practical choice depends on the final delivery region, sailing options and total destination cost. A West Coast port may offer a shorter ocean leg, while an East or Gulf Coast gateway may reduce inland movement for some destinations." }, { q: "Can you deliver directly to an Amazon warehouse?", a: "Delivery can be assessed when the seller has completed Amazon preparation and provides the valid shipment plan, labels and appointment requirements. Importer-of-record and customs responsibilities must be arranged separately and stated clearly." }] },
  { route: "shipping-from-china-to-mexico", country: "Mexico", shortName: "Mexico", ports: ["Manzanillo", "Lázaro Cárdenas", "Veracruz", "Ensenada"], inland: "Mexico City, Monterrey and other destinations", focus: ["FCL", "LCL", "Machinery", "Project cargo"], intro: "Compare Pacific and Gulf gateways using the consignee location, carrier service and inland-delivery plan.", importNote: "The Mexican importer should confirm importer registration, classification, permits, duties, taxes and customs-broker responsibilities before cargo leaves China.", optionNotes: ["Dedicated containers for regular commercial cargo, assessed with port handling and inland delivery.", "Consolidated freight for smaller shipments after confirming commodity acceptance and destination deconsolidation costs.", "Container, flat-rack or other solutions can be reviewed using verified machine dimensions, weight and packing.", "Oversized or heavy units require vessel, terminal, lifting and inland-route acceptance before booking."], routingNotes: ["Manzanillo and Lázaro Cárdenas are important Pacific references for central and western Mexico.", "Veracruz is a Gulf gateway that may suit eastern destinations depending on the available service.", "Ensenada may be considered for northwestern destinations; the customs broker and inland plan should be selected before dispatch."], importChecks: ["Mexican importer registration and customs broker confirmed", "Tariff classification and any NOM or permit requirements checked", "Spanish-language commercial information prepared when required", "Port charges, taxes and inland transport scope confirmed"], localFaqs: [{ q: "Should I use Manzanillo or Veracruz?", a: "Manzanillo often aligns with Pacific services from Asia, while Veracruz may suit some eastern destinations. The correct comparison includes sailing availability, customs arrangements and inland delivery—not ocean distance alone." }, { q: "Can machinery be shipped from China to Mexico?", a: "Yes, subject to import eligibility and carrier acceptance. Provide model, use, condition, dimensions, weight, packing, photographs and lifting information so container, flat-rack or project options can be assessed." }] },
  { route: "shipping-from-china-to-malaysia", country: "Malaysia", shortName: "Malaysia", ports: ["Port Klang", "Tanjung Pelepas", "Penang", "Kuantan"], inland: "Peninsular Malaysia and agreed East Malaysia destinations", focus: ["FCL", "LCL", "Air freight", "Supplier consolidation"], intro: "Plan short-haul Asia freight around the Malaysian destination, supplier locations and required delivery speed.", importNote: "The Malaysian importer should verify permits, taxes and any product-specific requirements before booking. Sabah and Sarawak destinations may require a different routing and handoff plan.", optionNotes: ["Dedicated containers for larger shipments to a gateway selected around the final Malaysian destination.", "Consolidated sea freight for smaller general cargo after confirming warehouse and destination handling.", "Useful for urgent or higher-value cargo after chargeable-weight, battery and commodity acceptance checks.", "Goods from several Chinese suppliers can be received, referenced and combined before export."], routingNotes: ["Port Klang is a principal gateway for the Klang Valley and central Peninsular Malaysia.", "Tanjung Pelepas can suit southern Peninsular Malaysia, while Penang can suit northern destinations.", "Kuantan serves the east coast; Sabah and Sarawak need separate East Malaysia routing rather than a generic Peninsular plan."], importChecks: ["Consignee registration and product permits checked", "SST, duty and tariff classification reviewed locally", "Peninsular or East Malaysia destination confirmed", "Batteries, food, cosmetics or controlled products declared before booking"], localFaqs: [{ q: "Is shipping to East Malaysia the same as Port Klang?", a: "No. Sabah and Sarawak normally require their own destination-port and handoff plan. State the final city or postcode so the quote does not incorrectly assume a Peninsular Malaysia delivery." }, { q: "Can multiple suppliers be consolidated in China?", a: "Yes. Each supplier should use the receiving reference and provide a packing list. Final measurements, cargo compatibility and the export plan are confirmed after all goods arrive." }] },
  { route: "shipping-from-china-to-ghana", country: "Ghana", shortName: "Ghana", ports: ["Tema", "Takoradi"], inland: "Accra, Kumasi and other destinations", focus: ["FCL", "LCL", "Vehicles", "Heavy machinery"], intro: "Use Tema or another suitable gateway based on cargo type, final destination and current vessel acceptance.", importNote: "The Ghanaian importer should confirm current customs, conformity, valuation, duty and destination-document requirements with a qualified local broker.", optionNotes: ["Dedicated containers for commercial cargo and equipment that fit standard or special container limits.", "Consolidated service for smaller general cargo, subject to commodity acceptance and destination deconsolidation arrangements.", "RoRo or containerized possibilities depend on vehicle condition, dimensions, documents and current carrier acceptance.", "Flat-rack, breakbulk or other project solutions require verified technical data and a discharge plan."], routingNotes: ["Tema is the main reference for Accra, Kumasi and much of Ghana's containerized trade.", "Takoradi may be relevant for western destinations or particular industrial and project requirements.", "Vehicle and heavy-cargo acceptance is service-specific and should not be assumed from a general sailing schedule."], importChecks: ["Importer and Ghana customs broker confirmed", "Classification, valuation and applicable conformity steps reviewed", "Vehicle age, condition and document eligibility checked where relevant", "Port release, handling equipment and inland delivery responsibilities defined"], localFaqs: [{ q: "Is Tema or Takoradi better for my shipment?", a: "Tema is commonly considered for containerized cargo and destinations around Accra, while Takoradi may suit some western or project requirements. Cargo type, service availability and inland delivery determine the final choice." }, { q: "Can vehicles be shipped from China to Ghana?", a: "Possible methods may include RoRo or containers, subject to current import rules and carrier acceptance. Provide the VIN or identification, dimensions, weight, condition, fuel or battery details and ownership documents for review." }] },
  { route: "shipping-from-china-to-mozambique", country: "Mozambique", shortName: "Mozambique", ports: ["Maputo", "Beira", "Nacala"], inland: "Mozambique and agreed regional destinations", focus: ["FCL", "Breakbulk", "Heavy machinery", "Project cargo"], intro: "Choose Maputo, Beira or Nacala by final delivery region, cargo handling requirements and available vessel service.", importNote: "The importer should confirm customs, permits, inspection requirements and the local transport plan. Oversized cargo requires port and inland-route checks before booking.", optionNotes: ["Container shipping for general cargo where the selected gateway and inland route form one workable plan.", "For cargo that cannot use standard containers, subject to lifting, terminal and vessel acceptance.", "Machinery planning uses verified weight, dimensions, lifting points, condition and destination equipment.", "A coordinated method statement can cover origin loading, ocean transport, discharge and agreed inland handoff."], routingNotes: ["Maputo can suit southern Mozambique and some regional corridors.", "Beira is a central gateway and may support inland destinations reached through the Beira corridor.", "Nacala can suit northern Mozambique; oversized cargo also needs bridge, road, escort and unloading checks."], importChecks: ["Importer, broker and destination permits confirmed", "Any pre-shipment inspection requirement checked", "Discharge equipment and port storage exposure reviewed", "Oversized inland route, permits, escorts and unloading site assessed"], localFaqs: [{ q: "Should cargo use Maputo, Beira or Nacala?", a: "Use the final delivery region as the starting point: Maputo for many southern movements, Beira for central corridors and Nacala for some northern destinations. Current vessel service and cargo handling capability must also be confirmed." }, { q: "What is needed for oversized machinery?", a: "Provide verified transport dimensions, gross weight, drawings, photographs, lifting points, centre of gravity and site access details. Port discharge and the complete inland route should be checked before booking." }] },
  { route: "shipping-from-china-to-uae", country: "the United Arab Emirates", shortName: "UAE", ports: ["Jebel Ali", "Khalifa Port"], inland: "Dubai, Abu Dhabi and other Emirates", focus: ["FCL", "LCL", "Air freight", "RoRo and project cargo"], intro: "Connect China-origin freight with a UAE gateway and a clearly defined free-zone, local-delivery or re-export scope.", importNote: "The UAE importer should confirm mainland or free-zone procedures, classification, permits, duties, VAT and consignee documentation before shipment.", optionNotes: ["Dedicated containers to Jebel Ali, Khalifa Port or another accepted gateway with the delivery scope defined.", "Consolidated cargo for smaller shipments, with destination handling and free-zone or mainland status confirmed.", "China-to-Dubai or Abu Dhabi air options for urgent cargo after chargeable-weight and acceptance checks.", "Vehicles, wheeled machinery and oversized units may use specialist services subject to vessel and terminal approval."], routingNotes: ["Jebel Ali is a major Dubai gateway for local delivery, free-zone activity and re-export planning.", "Khalifa Port can suit Abu Dhabi and other destinations depending on the carrier and inland scope.", "Mainland import, free-zone entry and re-export are different scopes and must be identified before quotation."], importChecks: ["Mainland, free-zone or re-export purpose confirmed", "Importer code, classification, permits, duty and VAT scope checked", "Commercial documents and country-of-origin requirements reviewed", "Final delivery access, unloading and consignee availability confirmed"], localFaqs: [{ q: "Can cargo be shipped to a UAE free zone?", a: "Yes, when the consignee, free-zone procedure and destination handoff are confirmed. A free-zone movement should not be quoted as if it were an ordinary UAE mainland import." }, { q: "Can you ship vehicles or machinery to Jebel Ali?", a: "Container, RoRo or project methods may be assessed using the unit's dimensions, weight, condition and documents. Carrier acceptance and UAE import or re-export requirements must be confirmed before booking." }] },
  { route: "shipping-from-china-to-saudi-arabia", country: "Saudi Arabia", shortName: "Saudi Arabia", ports: ["Jeddah Islamic Port", "King Abdulaziz Port, Dammam"], inland: "Riyadh and other Saudi destinations", focus: ["FCL", "LCL", "Vehicles", "Project cargo"], intro: "Select the Red Sea or Arabian Gulf gateway around the final Saudi destination, cargo and available service.", importNote: "The Saudi importer should confirm product conformity, importer documentation, permits, duties, VAT and clearance requirements with qualified local parties before shipment.", optionNotes: ["Dedicated containers with the Red Sea or Gulf gateway selected around the consignee and inland plan.", "Consolidated general cargo after confirming commodity acceptance, destination handling and documentation.", "RoRo or containerized vehicle options depend on eligibility, condition, specifications and current carrier acceptance.", "Heavy and oversized cargo requires engineering data, lifting review, port acceptance and an inland route survey."], routingNotes: ["Jeddah Islamic Port is a Red Sea gateway often considered for Jeddah and western Saudi destinations.", "King Abdulaziz Port in Dammam can suit the Eastern Province and some Riyadh movements.", "Riyadh cargo should be compared using the complete port-to-inland scope rather than ocean freight alone."], importChecks: ["Saudi importer details and customs broker confirmed", "SABER or other product-conformity scope checked where applicable", "Classification, permits, duty and VAT reviewed", "Arabic labels, commercial documents and final delivery requirements verified"], localFaqs: [{ q: "Should I ship through Jeddah or Dammam?", a: "Jeddah commonly aligns with western Saudi destinations, while Dammam can suit the Eastern Province and some Riyadh cargo. The final choice depends on sailing availability, clearance and total inland cost." }, { q: "Do products need conformity documents for Saudi Arabia?", a: "Some products may require conformity procedures or approvals. The Saudi importer should verify the current product-specific requirement before the goods are collected or shipped from China." }] },
];

export function getCountryRoute(route: string) { return countryRoutes.find(item => item.route === route); }

export const existingCountryRoutes = [
  { route: "shipping-from-china-to-australia", name: "Australia", ports: "Sydney · Melbourne · Brisbane · Fremantle" },
  { route: "shipping-from-china-to-nigeria", name: "Nigeria", ports: "Lagos · Apapa · suitable Nigeria ports" },
  { route: "shipping-from-china-to-kenya", name: "Kenya", ports: "Mombasa · Nairobi delivery coordination" },
];
