type ServiceCopy = { title: string; summary: string; detail: string; scope: string[]; preparation: string[] };
export type Service = { slug: string; number: string; image: string; alt: string; content: ServiceCopy };

export const services: Service[] = [
  { slug: "freight-forwarding", number: "01", image: "/images/sea-freight.webp", alt: "Container ship alongside port cranes", content: { title: "Freight Forwarding", summary: "One accountable China-side team coordinating suppliers, warehouses, trucks and international carriers.", detail: "Connect the individual steps of your shipment through a single origin-side contact. We review cargo readiness, transport options and handoffs before confirming the booking scope.", scope: ["China pickup and export preparation", "Ocean and air freight coordination", "DHL, FedEx and UPS express options", "Destination handoffs through local partners"], preparation: ["Product name, quantity and cargo photos", "Packed dimensions, gross weight and ready date", "Pickup address, destination and delivery scope"] } },
  { slug: "china-import-export", number: "02", image: "/images/procurement-warehouse.webp", alt: "Export cartons and order checking in a consolidation warehouse", content: { title: "China Procurement & Export", summary: "Practical origin support for purchasing, export preparation, shipment documents and dispatch.", detail: "Bring supplier communication, purchasing requirements and export arrangements into the same plan. Product requirements and destination acceptance should be confirmed before the goods are dispatched.", scope: ["China procurement coordination", "Supplier order and readiness follow-up", "Packing-list and shipment-document coordination", "Warehouse collection and export dispatch"], preparation: ["Product specification and supplier contact", "Order quantities and purchasing requirements", "Destination, packing requirements and target timing"] } },
  { slug: "air-freight", number: "03", image: "/images/air-freight.webp", alt: "Air cargo being loaded into a freight aircraft", content: { title: "Air Freight", summary: "Airport and door delivery options for urgent, valuable and time-sensitive international cargo.", detail: "Plan China-origin air shipments around the actual cargo and deadline. Compare flight routing together with origin handling and destination delivery, rather than treating flight time as the whole journey.", scope: ["China-to-worldwide air freight enquiries", "Airport-to-airport and onward delivery planning", "Packing and chargeable-weight review", "Urgent cargo and express-option comparison"], preparation: ["Product description, including batteries or liquids", "Number of pieces, packed sizes and gross weight", "Departure city, destination airport and deadline"] } },
  { slug: "oversize-freight", number: "04", image: "/images/project-cargo.webp", alt: "Heavy excavator secured on a low-bed transport trailer", content: { title: "Oversize Freight", summary: "Planning for machinery, long cargo, heavy pieces and shipments requiring special equipment.", detail: "An oversize shipment starts with a cargo and route review. Lifting, securing, road access and equipment availability are considered before a movement plan is agreed.", scope: ["Machinery and heavy-piece transport planning", "Special equipment and loading coordination", "Pickup access and route review", "Cargo securing and handoff preparation"], preparation: ["Transport dimensions and weight of every piece", "Photos, drawings, lifting points and centre of gravity", "Loading facilities, pickup access and destination"] } },
  { slug: "sea-freight", number: "05", image: "/images/sea-freight.webp", alt: "Container vessel at an international seaport", content: { title: "Global Sea Freight Booking", summary: "Our service network extends to the Middle East, Red Sea, India, and Pakistan; Europe, the Mediterranean; Africa; the east and west coasts of South America; North America; Australia; and Southeast Asia.", detail: "Global sea freight booking is a core TengYoda service. Our worldwide network supports major trade regions across Asia, the Middle East, Europe, Africa, the Americas and Australia. We coordinate collection, loading and documents around the cargo-ready date and confirmed sailing plan.", scope: ["Full-container-load bookings", "Less-than-container-load shipments", "Special-equipment booking enquiries", "Origin collection and container-loading coordination"], preparation: ["Packing list with dimensions, weight and volume", "Supplier location, cargo-ready date and destination port", "Preferred container type and delivery responsibilities"] } },
  { slug: "transport-warehousing", number: "06", image: "/images/china-domestic-trucking.webp", alt: "Container truck beside warehouse loading bays", content: { title: "Transport & Warehousing", summary: "Factory pickup, domestic trucking, warehouse receiving, consolidation and export delivery.", detail: "Keep goods moving between Chinese suppliers, warehouses and export terminals. Pickup windows, receiving instructions and cargo identification are agreed before arrival.", scope: ["China domestic road transport", "Factory pickup and warehouse delivery", "Receiving and shipment identification", "Dispatch to ports and airports"], preparation: ["Pickup and delivery addresses with contact details", "Cargo sizes, weight and loading conditions", "Receiving schedule and order references"] } },
  { slug: "roro-project-cargo", number: "07", image: "/images/project-cargo.webp", alt: "Heavy mobile machinery being prepared for port transport", content: { title: "RoRo & Project Cargo", summary: "Coordinated transport for vehicles, mobile equipment and complex multi-stage cargo projects.", detail: "Coordinate the stages of non-standard cargo transport with the actual equipment and route in mind. RoRo or alternative options depend on vessel acceptance, cargo condition and handling requirements.", scope: ["Vehicle and mobile-equipment shipment enquiries", "RoRo routing and carrier acceptance coordination", "Breakbulk and project cargo planning", "Multi-stage origin and destination handoffs"], preparation: ["Equipment model, dimensions, weight and condition", "Whether the unit is self-propelled and operational", "Photos, loading restrictions and destination"] } },
  { slug: "cargo-consolidation", number: "08", image: "/images/warehouse-operations.webp", alt: "Palletised supplier goods and a forklift in a consolidation warehouse", content: { title: "3PL & Consolidation", summary: "Receive goods from multiple suppliers, check incoming cargo and ship one consolidated order.", detail: "Combine supplier orders into one coordinated outbound plan. Agree the receiving checks, storage needs and dispatch trigger in advance so each supplier knows how to label and deliver the goods.", scope: ["Multi-supplier warehouse receiving", "Order and package-count checking", "Packing and consolidation coordination", "Combined export dispatch planning"], preparation: ["Supplier list and order references", "Expected arrival dates, carton counts and sizes", "Checking requirements and final shipping instructions"] } },
  { slug: "international-express", number: "09", image: "/images/international-express-parcels.webp", alt: "Sealed parcels on a roller conveyor before international dispatch", content: { title: "DHL, FedEx & UPS Express", summary: "International courier options from China for samples, parcels and smaller time-sensitive orders.", detail: "Compare DHL, FedEx and UPS options using the same cargo information and destination postcode. Confirm carrier acceptance, chargeable weight, surcharges and destination responsibilities before dispatch. Carrier names identify the services requested, not an exclusive partnership or agency status.", scope: ["DHL, FedEx and UPS service enquiries", "China-side collection and parcel preparation", "Packed size, weight and delivery-zone review", "Dispatch and shipment-document coordination"], preparation: ["Product description and any batteries, liquids or special contents", "Each parcel’s packed dimensions and gross weight", "Receiver address, postcode, contact number and required timing"] } },
];

export function getService(slug: string) { return services.find(service => service.slug === slug); }

export const coreServiceNames: Record<string, string> = {
  "sea-freight": "Global Sea Freight Booking",
  "air-freight": "Global Air Freight",
  "international-express": "DHL / FedEx / UPS Express",
  "china-import-export": "China Procurement",
  "cargo-consolidation": "Cargo Consolidation",
  "transport-warehousing": "China Road Transport",
};
export const coreServices = Object.keys(coreServiceNames).map(slug => services.find(service => service.slug === slug)!);
// Homepage selection is independent from the full service catalog and footer.
export const homepageServices = coreServices.map(service => service.slug === "transport-warehousing" ? getService("roro-project-cargo")! : service);
export const primaryService = getService("sea-freight")!;
export const supportingServices = coreServices.filter(service => service.slug !== primaryService.slug);
export const specialistServices = services.filter(service => !Object.hasOwn(coreServiceNames, service.slug));
export const orderedServices = [...coreServices, ...specialistServices];
export function serviceLabel(service: Service) { return coreServiceNames[service.slug] ?? service.content.title; }

const relatedServiceSlugs: Record<string, string[]> = {
  "transport-warehousing": ["cargo-consolidation", "sea-freight", "air-freight"],
  "sea-freight": ["cargo-consolidation", "transport-warehousing", "oversize-freight"],
  "air-freight": ["international-express", "cargo-consolidation", "transport-warehousing"],
  "international-express": ["air-freight", "china-import-export", "cargo-consolidation"],
  "china-import-export": ["cargo-consolidation", "international-express", "sea-freight"],
  "cargo-consolidation": ["china-import-export", "sea-freight", "transport-warehousing"],
  "freight-forwarding": ["sea-freight", "air-freight", "international-express"],
  "oversize-freight": ["roro-project-cargo", "transport-warehousing", "sea-freight"],
  "roro-project-cargo": ["oversize-freight", "sea-freight", "freight-forwarding"],
};
export function relatedServices(slug: string) { return (relatedServiceSlugs[slug] ?? []).map(getService).filter((service): service is Service => Boolean(service)); }
