import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { ArrowRight, Check, MessageCircle } from "lucide-react";
import { SiteHeader } from "@/components/site-header";
import { SiteFooter } from "@/components/site-footer";
import { EnquiryActions } from "@/components/enquiry-actions";
import { countryRoutes, getCountryRoute } from "@/lib/country-routes";
import { enquiryLinks } from "@/lib/company";
import { siteOrigin } from "@/lib/seo";
import { sitePath } from "@/lib/site-path";

export const dynamicParams = false;
export function generateStaticParams() { return countryRoutes.map(item => ({ route: item.route })); }

export async function generateMetadata({ params }: { params: Promise<{ route: string }> }): Promise<Metadata> {
  const item = getCountryRoute((await params).route);
  if (!item) return { title: "Shipping route not found", robots: { index: false } };
  const title = `Shipping from China to ${item.shortName} | Sea & Air Freight`;
  const description = `Plan shipping from China to ${item.shortName}: ${item.focus.join(", ")}, China pickup, consolidation and destination handoff coordination.`;
  const url = `${siteOrigin}/${item.route}`;
  return { title, description, alternates: { canonical: url }, openGraph: { title, description, url, type: "website", images: [{ url: `${siteOrigin}/images/sea-freight.webp`, alt: `Shipping from China to ${item.shortName}` }] } };
}

function JsonLd({ data }: { data: object }) { return <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(data).replace(/</g, "\\u003c") }} />; }

export default async function CountryShippingPage({ params }: { params: Promise<{ route: string }> }) {
  const item = getCountryRoute((await params).route);
  if (!item) notFound();
  const url = `${siteOrigin}/${item.route}`;
  const topic = `shipping from China to ${item.shortName}`;
  const quoteUrl = enquiryLinks(topic).whatsapp;
  const faqs = [
    { q: `How can I ship goods from China to ${item.shortName}?`, a: `The suitable method depends on cargo volume, urgency and handling needs. TengYoda can assess ${item.focus.join(", ")} using the final packed cargo and requested delivery scope.` },
    { q: `Which ports can be used for shipping to ${item.shortName}?`, a: `${item.ports.join(", ")} are useful routing references. The actual gateway depends on the final destination, cargo type, carrier service and current booking acceptance.` },
    { q: `How long does shipping from China to ${item.shortName} take?`, a: "Transit and total lead time vary by origin, destination, direct or transshipment routing, schedule, cargo acceptance, customs and delivery. A current routing is checked for each booking rather than presented as a permanent estimate." },
    { q: `How much does shipping from China to ${item.shortName} cost?`, a: "There is no permanent rate. Cost depends on dimensions, weight, method, pickup, route, season, destination charges and delivery scope. Request a shipment-specific quotation using final packed information." },
    { q: "Can TengYoda consolidate goods from multiple Chinese suppliers?", a: "Yes. Supplier cargo can be received at an agreed China warehouse and combined before export. Receiving references, checking scope and final measurements should be confirmed before dispatch." },
    { q: "What information is needed for a quote?", a: `Provide the product, packages, final dimensions and weights, pickup city, ready date and destination in ${item.shortName}. Identify batteries, liquids, chemicals, machinery or other special characteristics.` },
  ];
  const breadcrumb = { "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Home", item: `${siteOrigin}/` }, { "@type": "ListItem", position: 2, name: "Country shipping routes", item: `${siteOrigin}/shipping-routes` }, { "@type": "ListItem", position: 3, name: `Shipping from China to ${item.shortName}`, item: url }] };
  const service = { "@context": "https://schema.org", "@type": "Service", "@id": `${url}#service`, name: `Shipping from China to ${item.shortName}`, serviceType: "International freight forwarding from China", url, provider: { "@id": `${siteOrigin}/#organization`, name: "TengYoda Supply Chain Co., Ltd." }, areaServed: { "@type": "Country", name: item.country }, description: item.intro, hasOfferCatalog: { "@type": "OfferCatalog", name: `${item.shortName} freight options`, itemListElement: item.focus.map(name => ({ "@type": "Offer", itemOffered: { "@type": "Service", name } })) } };
  const faq = { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: faqs.map(x => ({ "@type": "Question", name: x.q, acceptedAnswer: { "@type": "Answer", text: x.a } })) };

  return <div className="site blog-site nigeria-page" id="top"><JsonLd data={breadcrumb} /><JsonLd data={service} /><JsonLd data={faq} /><SiteHeader active="services" /><main id="main-content" tabIndex={-1}>
    <section className="blog-hero service-hero editorial-hero nigeria-hero page-enter"><img className="editorial-photo" src={sitePath("/images/sea-freight.webp")} alt={`Shipping from China to ${item.shortName}`} width={1672} height={941} fetchPriority="high" /><div className="editorial-shade" /><div className="wrap"><nav className="blog-breadcrumb"><a href={sitePath("/")}>Home</a><span>/</span><a href={sitePath("/shipping-routes")}>Country routes</a><span>/</span><span>{item.shortName}</span></nav><span className="kicker light"><i />CHINA → {item.shortName.toUpperCase()}</span><h1>Shipping from China to {item.shortName}</h1><p>{item.intro} Plan {item.focus.join(", ")} with one China-side contact.</p><div className="nigeria-hero-actions"><a className="button accent" href="#quote-checklist">Prepare a quote request<ArrowRight /></a><a className="button outline-light" href={quoteUrl} target="_blank" rel="noreferrer">WhatsApp Vinson<MessageCircle /></a></div></div></section>
    <section className="nigeria-facts"><div className="wrap"><div><small>ORIGIN</small><strong>Major factories and ports in China</strong></div><div><small>DESTINATION PORTS</small><strong>{item.ports.join(" · ")}</strong></div><div><small>INLAND SCOPE</small><strong>{item.inland}</strong></div><div><small>QUOTE BASIS</small><strong>Actual cargo and confirmed scope</strong></div></div></section>
    <section className="section nigeria-overview"><div className="wrap nigeria-content-grid"><aside className="nigeria-toc"><h2>On this page</h2><nav><a href="#services">Freight options</a><a href="#ports">Ports and routing</a><a href="#process">Shipping process</a><a href="#quote-checklist">Quote checklist</a><a href="#faq">Questions</a></nav></aside><div className="nigeria-copy"><span className="kicker"><i />ROUTE OVERVIEW</span><h2>A shipment plan built around the cargo.</h2><p className="service-lead">TengYoda coordinates China pickup, warehouse or port handoffs, consolidation, export preparation and international freight. The selected route and service are confirmed against the final cargo, ready date and destination.</p><div className="nigeria-note"><strong>Confirm import requirements before shipment</strong><p>{item.importNote}</p></div></div></div></section>
    <section className="section nigeria-options" id="services"><div className="wrap"><div className="nigeria-heading"><span className="kicker"><i />FREIGHT OPTIONS</span><h2>Compare methods on the same scope.</h2></div><div className="scope-grid nigeria-service-grid">{item.focus.map((name, index) => <article key={name}><span>0{index + 1}</span><Check /><h3>{name}</h3><p>Assessed using the cargo dimensions, weight, characteristics, urgency, route availability and requested destination handoff.</p></article>)}</div></div></section>
    <section className="section nigeria-ports" id="ports"><div className="wrap nigeria-split"><div><span className="kicker"><i />PORTS & ROUTING</span><h2>{item.ports.join(", ")}.</h2><p>Potential China origins include Shanghai, Ningbo, Shenzhen, Guangzhou/Nansha, Qingdao, Tianjin and Xiamen. Supplier location and carrier service help determine the origin.</p><p>The destination gateway is selected using the final delivery location, current service, cargo type and destination handling. Routing can be direct or transshipped and is confirmed per booking.</p></div><figure><img src={sitePath(`/route-images/china-to-${item.route.replace("shipping-from-china-to-", "")}-route.png`)} alt={`Route map from major China ports to ${item.shortName}`} width={1536} height={1024} loading="lazy" /><figcaption>Route visualization based on named port coordinates; actual carrier, ports and schedule are confirmed per shipment.</figcaption></figure></div></section>
    <section className="section nigeria-process" id="process"><div className="wrap"><div className="nigeria-heading"><span className="kicker"><i />HOW IT WORKS</span><h2>From China supplier to destination handoff.</h2></div><ol>{[["Share the cargo", "Send products, packages, dimensions, weights, supplier locations, ready dates and destination."],["Compare methods", "Review suitable ocean, air or specialist cargo options."],["Define the scope", "Confirm origin, international freight and requested destination tasks and exclusions."],["Coordinate in China", "Arrange agreed collection, consolidation, export preparation and carrier handoff."],["Prepare arrival", "Share documents and arrival information for clearance, release and delivery planning."]].map(([h,c],i)=><li key={h}><span>0{i+1}</span><div><h3>{h}</h3><p>{c}</p></div></li>)}</ol></div></section>
    <section className="section nigeria-quote" id="quote-checklist"><div className="wrap nigeria-content-grid"><div><span className="kicker"><i />BEFORE YOU ENQUIRE</span><h2>Send complete cargo details.</h2><p>Accurate packed information reduces assumptions and helps compare options consistently.</p><EnquiryActions topic={topic} /></div><ul>{["Product description and HS code if known","Package count, dimensions and gross weight","Supplier locations and cargo-ready dates",`Port or final address in ${item.shortName}`,"Photos and packing method","Special handling or controlled characteristics","Requested Incoterm and delivery scope","Consignee and document requirements"].map(x=><li key={x}><Check />{x}</li>)}</ul></div></section>
    <section className="section nigeria-faq" id="faq"><div className="wrap nigeria-content-grid"><div><span className="kicker"><i />FAQ</span><h2>China-to-{item.shortName} shipping questions.</h2><p>Rates, schedules, customs and acceptance are confirmed shipment by shipment.</p></div><div>{faqs.map(x=><details key={x.q}><summary>{x.q}<span>+</span></summary><p>{x.a}</p></details>)}</div></div></section>
    <section className="blog-cta"><div className="wrap"><div><span className="kicker light"><i />A DIRECT CONVERSATION WITH VINSON</span><h2>Planning a shipment from China to {item.shortName}?</h2><p>Share the actual cargo and destination for a shipment-specific assessment.</p></div><EnquiryActions topic={topic} /></div></section>
  </main><SiteFooter /><a className="float-wa" href={quoteUrl} target="_blank" rel="noreferrer" aria-label="Contact Vinson on WhatsApp"><MessageCircle /></a></div>;
}
